### ISSUE TITLE
got error using GraphQL

### ISSUE THREAD

**Issue by azulkipli** [zerosecrets/docs#1]
I got this error when trying to get secret via [GrapQL here](https://github.com/zerosecrets/docs#graphql-api)

```
{
    "errors": [
        {
            "errorType": "UnknownOperationException",
            "message": "Unknown Operation Request."
        }
    ]
}
```
my query
```
query {
  secrets(zeroToken: "38xxxMyTokenStringHerexxxfd",pick: ["V_APP_SECRET"]) {
    name
    fields {
      name
      value
    }
  }
}
```

**Comment by Serator** [comment]
@azulkipli thanks for the feedback. There was an error in the url in the documentation - `https://core.tryzero.com/`~v1/~`graphql`. This has already been fixed. Let me know if you are still experiencing issues.
